### get all institutes
GET http://localhost:6100/institute-api/institutions

###
GET http://localhost:6100/medicine-api/medicines


###get a medicine by name
GET http://localhost:6100/medicine-api/medicine/name/PainAway

###delete a medicine by id
DELETE http://localhost:6100/medicine-api/medicine_delete/1


###
GET http://localhost:6100/family-api/family/673369fa1f1c7e63f4c5be21



###
POST http://localhost:6100/api/visits/register
Content-Type: application/json

{
  "employee_id": "6954bd3cf03344f236e9008f"
}

###
GET http://localhost:6100/api/visits/today

###
POST http://localhost:6100/api/medical-actions
Content-Type: application/json

{
  "employee_id": "6954bd3cf03344f236e9008f",
  "visit_id": null,
  "action_type": "DOCTOR_PRESCRIPTION",
  "source": "DOCTOR",
  "data": { "dummy": true }
}

###
POST http://localhost:6100/doctor-prescription-api/add
Content-Type: application/json

{
  "Institute_ID": "6954b2d1ad2cbe33ee781de6",
  "Employee_ID": "695608d568ee9b83741eb24f",
  "IsFamilyMember": false,
  "Medicines": [
    {
      "Medicine_Name": "Paracetamol",
      "Dosage": "1-0-1",
      "Duration": "5 days",
      "Quantity": 10
    }
  ],
  "Notes": "After food",
  "visit_id": null
}

###
POST http://localhost:6100/diagnosis-api/add
Content-Type: application/json

{
  "Institute_ID": "6954bd3cf03344f236e9008f",
  "Employee_ID": "6954bd3cf03344f236e9008f",
  "IsFamilyMember": false,
  "FamilyMember_ID": null,
  "Tests": [
    {
      "Test_Name": "Blood Sugar",
      "Result_Value": "120 mg/dL",
      "Reference_Range": "70-140",
      "Units": "mg/dL",
      "Remarks": "Normal"
    }
  ],
  "Diagnosis_Notes": "Routine check",
  "visit_id": null
}



###
http://localhost:6100/institute-api/analytics/696241bed5066b8df470b6b0
